// Canonical master dataset for all ICC-CNS 2027 committee members & leadership
export const officialCommitteeMembers = [
  {
    "id": "cm-01",
    "_id": "cm-01",
    "displayOrder": 1,
    "name": "Dr. L. Rathaiah",
    "role": "Chairman, Vignan's Group",
    "designation": "Chairman, Vignan's Group",
    "institution": "Vignan's Group",
    "org": "Vignan's Group",
    "category": "Chief Patrons",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788641543738-chairman.jpg",
    "imagePublicId": "member-1788641543738-chairman.jpg",
    "isActive": true
  },
  {
    "id": "cm-02",
    "_id": "cm-02",
    "displayOrder": 2,
    "name": "Sri L. Sri Krishna Devarayalu",
    "role": "Member of Parliament, Vice-Chairman, Vignan's Group",
    "designation": "Member of Parliament, Vice-Chairman, Vignan's Group",
    "institution": "Vignan's Group",
    "org": "Vignan's Group",
    "category": "Chief Patrons",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788642144248-Krishna-Lavu.webp",
    "imagePublicId": "member-1788642144248-Krishna-Lavu.webp",
    "isActive": true
  },
  {
    "id": "cm-03",
    "_id": "cm-03",
    "displayOrder": 3,
    "name": "Dr. Pavuluri Subba Rao",
    "role": "Chancellor, VFSTR",
    "designation": "Chancellor, VFSTR",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Patrons",
    "country": "India",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true
  },
  {
    "id": "cm-04",
    "_id": "cm-04",
    "displayOrder": 4,
    "name": "Dr. K. V. Krishna Kishore",
    "role": "Vice-Chancellor, VFSTR",
    "designation": "Vice-Chancellor, VFSTR",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Patrons",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788641585210-vice_chancellor.jpg",
    "imagePublicId": "member-1788641585210-vice_chancellor.jpg",
    "isActive": true
  },
  {
    "id": "cm-05",
    "_id": "cm-05",
    "displayOrder": 5,
    "name": "Dr. K. Meghana",
    "role": "CEO, VFSTR",
    "designation": "CEO, VFSTR",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Patrons",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788642343112-ceo_mam.jpg",
    "imagePublicId": "member-1788642343112-ceo_mam.jpg",
    "isActive": true
  },
  {
    "id": "cm-06",
    "_id": "cm-06",
    "displayOrder": 6,
    "name": "Dr P. M. V. Rao",
    "role": "Registrar, VFSTR",
    "designation": "Registrar, VFSTR",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Patrons",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788642386505-pmvrao.jpg",
    "imagePublicId": "member-1788642386505-pmvrao.jpg",
    "isActive": true
  },
  {
    "id": "cm-07",
    "_id": "cm-07",
    "displayOrder": 7,
    "name": "Prof. K.V.Krishna Kishore",
    "role": "Dean, School of Computing & Informatics",
    "designation": "Dean, School of Computing & Informatics",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "General Chair",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788642430670-vice_chancellor.jpg",
    "imagePublicId": "member-1788642430670-vice_chancellor.jpg",
    "isActive": true
  },
  {
    "id": "cm-08",
    "_id": "cm-08",
    "displayOrder": 8,
    "name": "Dr. S. V. Phani Kumar",
    "role": "Professor and HOD-CSE",
    "designation": "Professor and HOD-CSE",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "General Co-Chair",
    "country": "India",
    "imageUrl": "/uploads/committee/member-1788642445329-HOD_sir.webp",
    "imagePublicId": "member-1788642445329-HOD_sir.webp",
    "isActive": true
  },
  {
    "id": "intl-adv-chair-1",
    "_id": "intl-adv-chair-1",
    "name": "Prof. Dr. Nan Yang",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "ANU College of Systems and Society, Australian National University, Australia",
    "org": "ANU College of Systems and Society, Australian National University, Australia",
    "category": "International Advisory Chairs",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 9
  },
  {
    "id": "intl-adv-chair-2",
    "_id": "intl-adv-chair-2",
    "name": "Dr. Rui Dinis",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "FCT-UNL and Researcher, Instituto de Telecomunicações, Portugal",
    "org": "FCT-UNL and Researcher, Instituto de Telecomunicações, Portugal",
    "category": "International Advisory Chairs",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 10
  },
  {
    "id": "intl-adv-chair-3",
    "_id": "intl-adv-chair-3",
    "name": "Dr. Jinwei Liu",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Florida A&M University, United States",
    "org": "Florida A&M University, United States",
    "category": "International Advisory Chairs",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 11
  },
  {
    "id": "intl-adv-chair-4",
    "_id": "intl-adv-chair-4",
    "name": "Dr. Sinem Coleri",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Koc University, Turkey",
    "org": "Koc University, Turkey",
    "category": "International Advisory Chairs",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 12
  },
  {
    "id": "intl-adv-comm-1",
    "_id": "intl-adv-comm-1",
    "name": "Dr. Tomonobu Senjyu",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Professor, University of the Ryukyus, Okinawam, Japan",
    "org": "Professor, University of the Ryukyus, Okinawam, Japan",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 13
  },
  {
    "id": "intl-adv-comm-2",
    "_id": "intl-adv-comm-2",
    "name": "Dr. Francesco Zirlilli",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Professor (retired), Sapienza Universita, Roma, Italy",
    "org": "Professor (retired), Sapienza Universita, Roma, Italy",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 14
  },
  {
    "id": "intl-adv-comm-3",
    "_id": "intl-adv-comm-3",
    "name": "Dr. Dariusz Jacek Jakóbczak",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Koszalin University of Technology, Poland",
    "org": "Koszalin University of Technology, Poland",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 15
  },
  {
    "id": "intl-adv-comm-4",
    "_id": "intl-adv-comm-4",
    "name": "Dr. Addison Salazar",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Universitat Politècnica de València, Spain",
    "org": "Universitat Politècnica de València, Spain",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 16
  },
  {
    "id": "intl-adv-comm-5",
    "_id": "intl-adv-comm-5",
    "name": "Dr. Debdatta Sinha Roy",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Sr. Research Scientist, Oracle Retail Data Science R&D, Burlington, USA",
    "org": "Sr. Research Scientist, Oracle Retail Data Science R&D, Burlington, USA",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 17
  },
  {
    "id": "intl-adv-comm-6",
    "_id": "intl-adv-comm-6",
    "name": "Dr. Grigorios N. Beligiannis",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "University of Patras - Agrinio Campus, Greece",
    "org": "University of Patras - Agrinio Campus, Greece",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 18
  },
  {
    "id": "intl-adv-comm-7",
    "_id": "intl-adv-comm-7",
    "name": "Dr. Tzung-Pei Hong",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Professor, National University of Kaohsiung, Taiwan",
    "org": "Professor, National University of Kaohsiung, Taiwan",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 19
  },
  {
    "id": "intl-adv-comm-8",
    "_id": "intl-adv-comm-8",
    "name": "Dr. Ayodeji Olalekan Salau",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Afe Babalola University, Nigeria",
    "org": "Afe Babalola University, Nigeria",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 20
  },
  {
    "id": "intl-adv-comm-9",
    "_id": "intl-adv-comm-9",
    "name": "Dr. Leila Bayoudhi",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "University of Monastir, Tunisia",
    "org": "University of Monastir, Tunisia",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 21
  },
  {
    "id": "intl-adv-comm-10",
    "_id": "intl-adv-comm-10",
    "name": "Dr. Selim Hossain",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Hajee Mohammad Danesh Science & Technology University, Dinajpur, Bangladesh",
    "org": "Hajee Mohammad Danesh Science & Technology University, Dinajpur, Bangladesh",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 22
  },
  {
    "id": "intl-adv-comm-11",
    "_id": "intl-adv-comm-11",
    "name": "Dr. Yik-Chung Wu",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "The University of Hong Kong, Hong Kong",
    "org": "The University of Hong Kong, Hong Kong",
    "category": "International Advisory Committee",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 23
  },
  {
    "id": "cm-09",
    "_id": "cm-09",
    "displayOrder": 24,
    "name": "Ching-Hsien Hsu",
    "role": "Advisory Committee Member",
    "designation": "Asia University",
    "institution": "Asia University",
    "org": "Asia University",
    "category": "International Advisory Committee",
    "country": "Taiwan",
    "isActive": true
  },
  {
    "id": "cm-10",
    "_id": "cm-10",
    "displayOrder": 25,
    "name": "Ren-Hung Hwang",
    "role": "Advisory Committee Member",
    "designation": "Asia University",
    "institution": "Asia University",
    "org": "Asia University",
    "category": "International Advisory Committee",
    "country": "Taiwan",
    "isActive": true
  },
  {
    "id": "cm-11",
    "_id": "cm-11",
    "displayOrder": 26,
    "name": "Dr. S. Deva Kumar",
    "role": "Conference Chair",
    "designation": "Conference Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Conference Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-12",
    "_id": "cm-12",
    "displayOrder": 27,
    "name": "Dr. M. Uma Devi",
    "role": "Conference Co-Chair",
    "designation": "Conference Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Conference Co-Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-13",
    "_id": "cm-13",
    "displayOrder": 28,
    "name": "Dr. P Jhansi Lakshmi",
    "role": "Conference Co-Chair",
    "designation": "Conference Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Conference Co-Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-14",
    "_id": "cm-14",
    "displayOrder": 29,
    "name": "Dr. B. Suvarna",
    "role": "Conference Co-Chair",
    "designation": "Conference Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Conference Co-Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-15",
    "_id": "cm-15",
    "displayOrder": 30,
    "name": "Dr. Ch. Siva Koteshwara Rao",
    "role": "Organizing Chair",
    "designation": "Organizing Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "honorary-chair-1",
    "_id": "honorary-chair-1",
    "name": "Prof. Jinsong Wu",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "University of Chile, Chile",
    "org": "University of Chile, Chile",
    "category": "Honorary Chairs",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 31
  },
  {
    "id": "honorary-chair-2",
    "_id": "honorary-chair-2",
    "name": "Dr. Alvaro Rocha",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Vice-Chair of IEEE SMC Portugal Chapter, Professor ISEG, University of Lisbon, Lisboa, Portugal",
    "org": "Vice-Chair of IEEE SMC Portugal Chapter, Professor ISEG, University of Lisbon, Lisboa, Portugal",
    "category": "Honorary Chairs",
    "country": "",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 32
  },
  {
    "id": "cm-16",
    "_id": "cm-16",
    "displayOrder": 33,
    "name": "Dr. S. Satish Kumar",
    "role": "Technical Chair",
    "designation": "Technical Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-17",
    "_id": "cm-17",
    "displayOrder": 34,
    "name": "Dr. D. Yakobu",
    "role": "Technical Chair",
    "designation": "Technical Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-18",
    "_id": "cm-18",
    "displayOrder": 35,
    "name": "Dr. R. Prathap Kumar",
    "role": "Technical Co-Chair",
    "designation": "Technical Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Co-Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-19",
    "_id": "cm-19",
    "displayOrder": 36,
    "name": "Dr. E. Deepak",
    "role": "Technical Co-Chair",
    "designation": "Technical Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Co-Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-20",
    "_id": "cm-20",
    "displayOrder": 37,
    "name": "Dr. M. Raja Rao",
    "role": "Technical Co-Chair",
    "designation": "Technical Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Co-Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-22",
    "_id": "cm-22",
    "displayOrder": 38,
    "name": "Dr. G. Sravya",
    "role": "Technical Co-Chair",
    "designation": "Technical Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Co-Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-23",
    "_id": "cm-23",
    "displayOrder": 39,
    "name": "Dr. Sk. Reehana",
    "role": "Technical Co-Chair",
    "designation": "Technical Co-Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Co-Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-24",
    "_id": "cm-24",
    "displayOrder": 40,
    "name": "Dr. James Deva Koresh",
    "role": "Publication Chair",
    "designation": "Publication Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publication Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-25",
    "_id": "cm-25",
    "displayOrder": 41,
    "name": "Dr. Vijitha",
    "role": "Publication Chair",
    "designation": "Publication Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publication Chairs",
    "country": "India",
    "isActive": true
  },
  {
    "id": "nat-adv-comm-1",
    "_id": "nat-adv-comm-1",
    "name": "Dr. Gopal Rawat",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Indian Institute of Technology Mandi, India",
    "org": "Indian Institute of Technology Mandi, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 42
  },
  {
    "id": "nat-adv-comm-2",
    "_id": "nat-adv-comm-2",
    "name": "Dr. B. K. Roy",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Silchar, India",
    "org": "National Institute of Technology Silchar, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 43
  },
  {
    "id": "nat-adv-comm-3",
    "_id": "nat-adv-comm-3",
    "name": "Dr. Umesh C. Pati",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Rourkela, India",
    "org": "National Institute of Technology Rourkela, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 44
  },
  {
    "id": "nat-adv-comm-4",
    "_id": "nat-adv-comm-4",
    "name": "Dr. Shailendra K. Dwivedi",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Maulana Azad National Institute of Technology Bhopal, India",
    "org": "Maulana Azad National Institute of Technology Bhopal, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 45
  },
  {
    "id": "nat-adv-comm-5",
    "_id": "nat-adv-comm-5",
    "name": "Dr. Brijesh Kumar",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Indira Gandhi Delhi Technical University, India",
    "org": "Indira Gandhi Delhi Technical University, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 46
  },
  {
    "id": "nat-adv-comm-6",
    "_id": "nat-adv-comm-6",
    "name": "Dr. M. Thenmozhi",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Puducherry Technological University, India",
    "org": "Puducherry Technological University, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 47
  },
  {
    "id": "nat-adv-comm-7",
    "_id": "nat-adv-comm-7",
    "name": "Dr. K. L. V. Sai Prakash Sakuru",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Warangal, India",
    "org": "National Institute of Technology Warangal, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 48
  },
  {
    "id": "nat-adv-comm-8",
    "_id": "nat-adv-comm-8",
    "name": "Dr. Tajinder Singh Arora",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Uttarakhand, India",
    "org": "National Institute of Technology Uttarakhand, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 49
  },
  {
    "id": "nat-adv-comm-9",
    "_id": "nat-adv-comm-9",
    "name": "Dr. Subhojit Ghosh",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Raipur, India",
    "org": "National Institute of Technology Raipur, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 50
  },
  {
    "id": "nat-adv-comm-10",
    "_id": "nat-adv-comm-10",
    "name": "Dr. Anuradha Banerjee",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Kalyani Government Engineering College, India",
    "org": "Kalyani Government Engineering College, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 51
  },
  {
    "id": "nat-adv-comm-11",
    "_id": "nat-adv-comm-11",
    "name": "Dr. Tejavathu Ramesh",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Andhra Pradesh, India",
    "org": "National Institute of Technology Andhra Pradesh, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 52
  },
  {
    "id": "nat-adv-comm-12",
    "_id": "nat-adv-comm-12",
    "name": "Dr. Amit Rathi",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Manipal University Jaipur, India",
    "org": "Manipal University Jaipur, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 53
  },
  {
    "id": "nat-adv-comm-13",
    "_id": "nat-adv-comm-13",
    "name": "Dr. Virender Ranga",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Delhi Technological University, India",
    "org": "Delhi Technological University, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 54
  },
  {
    "id": "nat-adv-comm-14",
    "_id": "nat-adv-comm-14",
    "name": "Dr. Ngangbam Herojit Singh",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Agartala, India",
    "org": "National Institute of Technology Agartala, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 55
  },
  {
    "id": "nat-adv-comm-15",
    "_id": "nat-adv-comm-15",
    "name": "Dr. Jayendra Kumar",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Jamshedpur, India",
    "org": "National Institute of Technology Jamshedpur, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 56
  },
  {
    "id": "nat-adv-comm-16",
    "_id": "nat-adv-comm-16",
    "name": "Dr. Anirban Banik",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Sikkim, India",
    "org": "National Institute of Technology Sikkim, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 57
  },
  {
    "id": "nat-adv-comm-17",
    "_id": "nat-adv-comm-17",
    "name": "Dr. S. Chitra",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Government College of Technology Coimbatore, India",
    "org": "Government College of Technology Coimbatore, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 58
  },
  {
    "id": "nat-adv-comm-18",
    "_id": "nat-adv-comm-18",
    "name": "Dr. J. Satheesh Kumar",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Dayananda Sagar College of Engineering, India",
    "org": "Dayananda Sagar College of Engineering, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 59
  },
  {
    "id": "nat-adv-comm-19",
    "_id": "nat-adv-comm-19",
    "name": "Dr. John Clement Singh C",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Kings Engineering College, India",
    "org": "Kings Engineering College, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 60
  },
  {
    "id": "nat-adv-comm-20",
    "_id": "nat-adv-comm-20",
    "name": "Dr. Nandhini Gayathri",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "SASTRA University, India",
    "org": "SASTRA University, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 61
  },
  {
    "id": "nat-adv-comm-21",
    "_id": "nat-adv-comm-21",
    "name": "Dr. Dilip Singh Sisodia",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "National Institute of Technology Raipur, India",
    "org": "National Institute of Technology Raipur, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 62
  },
  {
    "id": "nat-adv-comm-22",
    "_id": "nat-adv-comm-22",
    "name": "Dr. Angeline Vijila D",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "PSG College of Technology, India",
    "org": "PSG College of Technology, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 63
  },
  {
    "id": "nat-adv-comm-23",
    "_id": "nat-adv-comm-23",
    "name": "Dr. Bhargava Rama",
    "role": "",
    "designation": "",
    "department": "",
    "institution": "Indian Institute of Technology Roorkee, India",
    "org": "Indian Institute of Technology Roorkee, India",
    "category": "National Advisory Committee",
    "country": "India",
    "bio": "",
    "email": "",
    "imageUrl": null,
    "imagePublicId": null,
    "isActive": true,
    "displayOrder": 64
  },
  {
    "id": "cm-26",
    "_id": "cm-26",
    "displayOrder": 65,
    "name": "Dr. G. Balu Narasimha Rao G",
    "role": "Finance Chair",
    "designation": "Finance Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Finance Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-27",
    "_id": "cm-27",
    "displayOrder": 66,
    "name": "Dr. Sunil Babu",
    "role": "Publicity Chair",
    "designation": "Publicity Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-28",
    "_id": "cm-28",
    "displayOrder": 67,
    "name": "Dr. Vinoj",
    "role": "Publicity Chair",
    "designation": "Publicity Chair",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Chair",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-29",
    "_id": "cm-29",
    "displayOrder": 68,
    "name": "Dr. Simhadri Chinna Gopi",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-30",
    "_id": "cm-30",
    "displayOrder": 69,
    "name": "Dr. R. Renugadevi",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-31",
    "_id": "cm-31",
    "displayOrder": 70,
    "name": "Dr. Krishna Reddy",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-32",
    "_id": "cm-32",
    "displayOrder": 71,
    "name": "Dr. M. Vijay Meyyapan",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-33",
    "_id": "cm-33",
    "displayOrder": 72,
    "name": "Dr. M. Bhargavi",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-34",
    "_id": "cm-34",
    "displayOrder": 73,
    "name": "Mr. Sk. Sikindar",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-35",
    "_id": "cm-35",
    "displayOrder": 74,
    "name": "Mrs. G. Navya",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-36",
    "_id": "cm-36",
    "displayOrder": 75,
    "name": "Mr. A. Kalyan Babu",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-37",
    "_id": "cm-37",
    "displayOrder": 76,
    "name": "Dr. Phanindra T",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-38",
    "_id": "cm-38",
    "displayOrder": 77,
    "name": "Mr. Loganathan M",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-39",
    "_id": "cm-39",
    "displayOrder": 78,
    "name": "Mrs. V. Anusha",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-40",
    "_id": "cm-40",
    "displayOrder": 79,
    "name": "Mrs. S.Anitha",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-41",
    "_id": "cm-41",
    "displayOrder": 80,
    "name": "Mrs. L. Yuvana Lagadapati",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-43",
    "_id": "cm-43",
    "displayOrder": 81,
    "name": "Mrs. V. Tejaswi",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-44",
    "_id": "cm-44",
    "displayOrder": 82,
    "name": "Mr. P Kiran Kumar Raja",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-45",
    "_id": "cm-45",
    "displayOrder": 83,
    "name": "Dr G Veerabhadra Chary",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-46",
    "_id": "cm-46",
    "displayOrder": 84,
    "name": "Dr. M. Rajarao",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-47",
    "_id": "cm-47",
    "displayOrder": 85,
    "name": "Mr. B. Anil Babu",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-48",
    "_id": "cm-48",
    "displayOrder": 86,
    "name": "Mrs. K. Pavani",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-49",
    "_id": "cm-49",
    "displayOrder": 87,
    "name": "Mr. O. Gandhi",
    "role": "Technical Program Committee Member",
    "designation": "Technical Program Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Technical Program Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-50",
    "_id": "cm-50",
    "displayOrder": 88,
    "name": "Mr. P. Vijaya Babu",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-51",
    "_id": "cm-51",
    "displayOrder": 89,
    "name": "Ms. B. Jyothika",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-52",
    "_id": "cm-52",
    "displayOrder": 90,
    "name": "Mr. Syed Nafees Ahamed",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-53",
    "_id": "cm-53",
    "displayOrder": 91,
    "name": "Mrs. D. Tipura",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-54",
    "_id": "cm-54",
    "displayOrder": 92,
    "name": "Ms. K. Raja Rajeswari",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-55",
    "_id": "cm-55",
    "displayOrder": 93,
    "name": "Ms. K. Mercy Bhishayathi",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-56",
    "_id": "cm-56",
    "displayOrder": 94,
    "name": "Mrs. M. Sumalatha",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-57",
    "_id": "cm-57",
    "displayOrder": 95,
    "name": "Mrs. J Davanika",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-58",
    "_id": "cm-58",
    "displayOrder": 96,
    "name": "Mrs. N. Archana",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-59",
    "_id": "cm-59",
    "displayOrder": 97,
    "name": "Ms. K. Vyshnavi",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-60",
    "_id": "cm-60",
    "displayOrder": 98,
    "name": "Mr. Kumar Devapogu",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-61",
    "_id": "cm-61",
    "displayOrder": 99,
    "name": "Mrs. R. Lalitha",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-62",
    "_id": "cm-62",
    "displayOrder": 100,
    "name": "Ms. Y. Sravani",
    "role": "Publicity Committee Member",
    "designation": "Publicity Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Publicity Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-63",
    "_id": "cm-63",
    "displayOrder": 101,
    "name": "Ms. M. Sirisha",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-64",
    "_id": "cm-64",
    "displayOrder": 102,
    "name": "Dr. Shyam Sunder Jannu Soloman",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-65",
    "_id": "cm-65",
    "displayOrder": 103,
    "name": "Mr. B. Krishnakanth",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-66",
    "_id": "cm-66",
    "displayOrder": 104,
    "name": "Mrs. G.Siva Naga Malleswari",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-67",
    "_id": "cm-67",
    "displayOrder": 105,
    "name": "Mrs. K. Jyotsna",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-68",
    "_id": "cm-68",
    "displayOrder": 106,
    "name": "Mr. E. Akhil Babu",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-69",
    "_id": "cm-69",
    "displayOrder": 107,
    "name": "Ms. Sk. Sajida Sultana",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-70",
    "_id": "cm-70",
    "displayOrder": 108,
    "name": "Mrs. V. Sai Spandana",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-71",
    "_id": "cm-71",
    "displayOrder": 109,
    "name": "Mr. D. Balakotaiah",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-72",
    "_id": "cm-72",
    "displayOrder": 110,
    "name": "Mr. P. Venkata Rajulu",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-73",
    "_id": "cm-73",
    "displayOrder": 111,
    "name": "Mr. Sk. Dehtaj",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-74",
    "_id": "cm-74",
    "displayOrder": 112,
    "name": "Ms. Bhavanari Satya Gnyana Sri",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-75",
    "_id": "cm-75",
    "displayOrder": 113,
    "name": "Ms. K. Divya",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-76",
    "_id": "cm-76",
    "displayOrder": 114,
    "name": "Mr. G. Murali",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-77",
    "_id": "cm-77",
    "displayOrder": 115,
    "name": "Mr. K Pavan Kumar",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-78",
    "_id": "cm-78",
    "displayOrder": 116,
    "name": "Mr. M. Anil",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-79",
    "_id": "cm-79",
    "displayOrder": 117,
    "name": "Ms. U. Vara Lakshmi",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-80",
    "_id": "cm-80",
    "displayOrder": 118,
    "name": "Mr. P. Vamsi Krishna",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-81",
    "_id": "cm-81",
    "displayOrder": 119,
    "name": "Ms. P. Deepthi Sowmya",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-82",
    "_id": "cm-82",
    "displayOrder": 120,
    "name": "Ms. K. Anitha",
    "role": "Organizing Committee Member",
    "designation": "Organizing Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Organizing Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-83",
    "_id": "cm-83",
    "displayOrder": 121,
    "name": "Mrs. Ch. Pushya",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-84",
    "_id": "cm-84",
    "displayOrder": 122,
    "name": "Mr. N. Brahma Naidu",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-85",
    "_id": "cm-85",
    "displayOrder": 123,
    "name": "Mrs. Ch. Swarna Lalitha",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-86",
    "_id": "cm-86",
    "displayOrder": 124,
    "name": "Mrs. K. Sravanthi",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-87",
    "_id": "cm-87",
    "displayOrder": 125,
    "name": "Ms. K. Deepika Sri Sai",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-88",
    "_id": "cm-88",
    "displayOrder": 126,
    "name": "Ms. G. Tejaswi",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-89",
    "_id": "cm-89",
    "displayOrder": 127,
    "name": "Mrs. Sk. Nazeema",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-90",
    "_id": "cm-90",
    "displayOrder": 128,
    "name": "Mrs. G Prasanthi",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  },
  {
    "id": "cm-91",
    "_id": "cm-91",
    "displayOrder": 129,
    "name": "Ms. A. Gopya Sri",
    "role": "Protocol & Hospitality Committee Member",
    "designation": "Protocol & Hospitality Committee Member",
    "institution": "VFSTR (Deemed to be University)",
    "org": "VFSTR (Deemed to be University)",
    "category": "Protocol and Hospitality Committee",
    "country": "India",
    "isActive": true
  }
];
