export const officialCommitteeMembers = [
  // CHIEF PATRONS (1 - 2)
  {
    id: "cm-01",
    _id: "cm-01",
    displayOrder: 1,
    name: "Dr. L. Rathaiah",
    role: "Chairman, Vignan's Group",
    designation: "Chairman, Vignan's Group",
    institution: "Vignan's Group",
    org: "Vignan's Group",
    category: "Chief Patrons",
    country: "India",
    imageUrl: "/uploads/committee/member-1788641543738-chairman.jpg",
    imagePublicId: "member-1788641543738-chairman.jpg",
    isActive: true
  },
  {
    id: "cm-02",
    _id: "cm-02",
    displayOrder: 2,
    name: "Sri L. Sri Krishna Devarayalu",
    role: "Member of Parliament, Vice-Chairman, Vignan's Group",
    designation: "Member of Parliament, Vice-Chairman, Vignan's Group",
    institution: "Vignan's Group",
    org: "Vignan's Group",
    category: "Chief Patrons",
    country: "India",
    imageUrl: "/uploads/committee/member-1788642144248-Krishna-Lavu.webp",
    imagePublicId: "member-1788642144248-Krishna-Lavu.webp",
    isActive: true
  },

  // PATRONS (3 - 6)
  {
    id: "cm-03",
    _id: "cm-03",
    displayOrder: 3,
    name: "Dr. Pavuluri Subba Rao",
    role: "Chancellor, VFSTR",
    designation: "Chancellor, VFSTR",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Patrons",
    country: "India",
    imageUrl: null,
    imagePublicId: null,
    isActive: true
  },
  {
    id: "cm-04",
    _id: "cm-04",
    displayOrder: 4,
    name: "Dr. K. V. Krishna Kishore",
    role: "Vice-Chancellor, VFSTR",
    designation: "Vice-Chancellor, VFSTR",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Patrons",
    country: "India",
    imageUrl: "/uploads/committee/member-1788641585210-vice_chancellor.jpg",
    imagePublicId: "member-1788641585210-vice_chancellor.jpg",
    isActive: true
  },
  {
    id: "cm-05",
    _id: "cm-05",
    displayOrder: 5,
    name: "Dr. K. Meghana",
    role: "CEO, VFSTR",
    designation: "CEO, VFSTR",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Patrons",
    country: "India",
    imageUrl: "/uploads/committee/member-1788642343112-ceo_mam.jpg",
    imagePublicId: "member-1788642343112-ceo_mam.jpg",
    isActive: true
  },
  {
    id: "cm-06",
    _id: "cm-06",
    displayOrder: 6,
    name: "Dr P. M. V. Rao",
    role: "Registrar, VFSTR",
    designation: "Registrar, VFSTR",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Patrons",
    country: "India",
    imageUrl: "/uploads/committee/member-1788642386505-pmvrao.jpg",
    imagePublicId: "member-1788642386505-pmvrao.jpg",
    isActive: true
  },

  // GENERAL CHAIR (7)
  {
    id: "cm-07",
    _id: "cm-07",
    displayOrder: 7,
    name: "Prof. K.V.Krishna Kishore",
    role: "Dean, School of Computing & Informatics",
    designation: "Dean, School of Computing & Informatics",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "General Chair",
    country: "India",
    imageUrl: "/uploads/committee/member-1788642430670-vice_chancellor.jpg",
    imagePublicId: "member-1788642430670-vice_chancellor.jpg",
    isActive: true
  },

  // GENERAL CO-CHAIR (8)
  {
    id: "cm-08",
    _id: "cm-08",
    displayOrder: 8,
    name: "Dr. S. V. Phani Kumar",
    role: "Professor and HOD-CSE",
    designation: "Professor and HOD-CSE",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "General Co-Chair",
    country: "India",
    imageUrl: "/uploads/committee/member-1788642445329-HOD_sir.webp",
    imagePublicId: "member-1788642445329-HOD_sir.webp",
    isActive: true
  },

  // ADVISORY COMMITTEE (9 - 10)
  {
    id: "cm-09",
    _id: "cm-09",
    displayOrder: 9,
    name: "Ching-Hsien Hsu",
    role: "Advisory Committee Member",
    designation: "Asia University",
    institution: "Asia University",
    org: "Asia University",
    category: "Advisory Committee",
    country: "Taiwan",
    isActive: true
  },
  {
    id: "cm-10",
    _id: "cm-10",
    displayOrder: 10,
    name: "Ren-Hung Hwang",
    role: "Advisory Committee Member",
    designation: "Asia University",
    institution: "Asia University",
    org: "Asia University",
    category: "Advisory Committee",
    country: "Taiwan",
    isActive: true
  },

  // CONFERENCE CHAIR (11)
  {
    id: "cm-11",
    _id: "cm-11",
    displayOrder: 11,
    name: "Dr. S. Deva Kumar",
    role: "Conference Chair",
    designation: "Conference Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Conference Chair",
    country: "India",
    isActive: true
  },

  // CONFERENCE CO-CHAIR (12 - 14)
  {
    id: "cm-12",
    _id: "cm-12",
    displayOrder: 12,
    name: "Dr. M. Uma Devi",
    role: "Conference Co-Chair",
    designation: "Conference Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Conference Co-Chair",
    country: "India",
    isActive: true
  },
  {
    id: "cm-13",
    _id: "cm-13",
    displayOrder: 13,
    name: "Dr. P Jhansi Lakshmi",
    role: "Conference Co-Chair",
    designation: "Conference Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Conference Co-Chair",
    country: "India",
    isActive: true
  },
  {
    id: "cm-14",
    _id: "cm-14",
    displayOrder: 14,
    name: "Dr. B. Suvarna",
    role: "Conference Co-Chair",
    designation: "Conference Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Conference Co-Chair",
    country: "India",
    isActive: true
  },

  // ORGANIZING CHAIR (15)
  {
    id: "cm-15",
    _id: "cm-15",
    displayOrder: 15,
    name: "Dr. Ch. Siva Koteshwara Rao",
    role: "Organizing Chair",
    designation: "Organizing Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Chair",
    country: "India",
    isActive: true
  },

  // TECHNICAL CHAIRS (16 - 17)
  {
    id: "cm-16",
    _id: "cm-16",
    displayOrder: 16,
    name: "Dr. S. Satish Kumar",
    role: "Technical Chair",
    designation: "Technical Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-17",
    _id: "cm-17",
    displayOrder: 17,
    name: "Dr. D. Yakobu",
    role: "Technical Chair",
    designation: "Technical Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Chairs",
    country: "India",
    isActive: true
  },

  // TECHNICAL CO-CHAIRS (18 - 23)
  {
    id: "cm-18",
    _id: "cm-18",
    displayOrder: 18,
    name: "Dr. R. Prathap Kumar",
    role: "Technical Co-Chair",
    designation: "Technical Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Co-Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-19",
    _id: "cm-19",
    displayOrder: 19,
    name: "Dr. E. Deepak",
    role: "Technical Co-Chair",
    designation: "Technical Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Co-Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-20",
    _id: "cm-20",
    displayOrder: 20,
    name: "Dr. M. Raja Rao",
    role: "Technical Co-Chair",
    designation: "Technical Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Co-Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-21",
    _id: "cm-21",
    displayOrder: 21,
    name: "Dr. Shyam Sundar Jannu Soloman",
    role: "Technical Co-Chair",
    designation: "Technical Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Co-Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-22",
    _id: "cm-22",
    displayOrder: 22,
    name: "Dr. G. Sravya",
    role: "Technical Co-Chair",
    designation: "Technical Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Co-Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-23",
    _id: "cm-23",
    displayOrder: 23,
    name: "Dr. Sk. Reehana",
    role: "Technical Co-Chair",
    designation: "Technical Co-Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Co-Chairs",
    country: "India",
    isActive: true
  },

  // PUBLICATION CHAIRS (24 - 25)
  {
    id: "cm-24",
    _id: "cm-24",
    displayOrder: 24,
    name: "Dr. James Deva Koresh",
    role: "Publication Chair",
    designation: "Publication Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publication Chairs",
    country: "India",
    isActive: true
  },
  {
    id: "cm-25",
    _id: "cm-25",
    displayOrder: 25,
    name: "Dr. Vijitha",
    role: "Publication Chair",
    designation: "Publication Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publication Chairs",
    country: "India",
    isActive: true
  },

  // FINANCE CHAIR (26)
  {
    id: "cm-26",
    _id: "cm-26",
    displayOrder: 26,
    name: "Dr. G. Balu Narasimha Rao G",
    role: "Finance Chair",
    designation: "Finance Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Finance Chair",
    country: "India",
    isActive: true
  },

  // PUBLICITY CHAIR (27 - 28)
  {
    id: "cm-27",
    _id: "cm-27",
    displayOrder: 27,
    name: "Dr. Sunil Babu",
    role: "Publicity Chair",
    designation: "Publicity Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Chair",
    country: "India",
    isActive: true
  },
  {
    id: "cm-28",
    _id: "cm-28",
    displayOrder: 28,
    name: "Dr. Vinoj",
    role: "Publicity Chair",
    designation: "Publicity Chair",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Chair",
    country: "India",
    isActive: true
  },

  // ORGANIZING COMMITTEE (29 - 33)
  {
    id: "cm-29",
    _id: "cm-29",
    displayOrder: 29,
    name: "Dr. Simhadri Chinna Gopi",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-30",
    _id: "cm-30",
    displayOrder: 30,
    name: "Dr. R. Renugadevi",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-31",
    _id: "cm-31",
    displayOrder: 31,
    name: "Dr. Krishna Reddy",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-32",
    _id: "cm-32",
    displayOrder: 32,
    name: "Dr. M. Vijay Meyyapan",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-33",
    _id: "cm-33",
    displayOrder: 33,
    name: "Dr. M. Bhargavi",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },

  // TECHNICAL PROGRAM COMMITTEE (34 - 49)
  {
    id: "cm-34",
    _id: "cm-34",
    displayOrder: 34,
    name: "Mr. Sk. Sikindar",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-35",
    _id: "cm-35",
    displayOrder: 35,
    name: "Mrs. G. Navya",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-36",
    _id: "cm-36",
    displayOrder: 36,
    name: "Mr. A. Kalyan Babu",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-37",
    _id: "cm-37",
    displayOrder: 37,
    name: "Dr. Phanindra T",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-38",
    _id: "cm-38",
    displayOrder: 38,
    name: "Mr. Loganathan M",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-39",
    _id: "cm-39",
    displayOrder: 39,
    name: "Mrs. V. Anusha",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-40",
    _id: "cm-40",
    displayOrder: 40,
    name: "Mrs. S.Anitha",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-41",
    _id: "cm-41",
    displayOrder: 41,
    name: "Mrs. L. Yuvana Lagadapati",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-42",
    _id: "cm-42",
    displayOrder: 42,
    name: "Dr. R. Prathap Kumar",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-43",
    _id: "cm-43",
    displayOrder: 43,
    name: "Mrs. V. Tejaswi",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-44",
    _id: "cm-44",
    displayOrder: 44,
    name: "Mr. P Kiran Kumar Raja",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-45",
    _id: "cm-45",
    displayOrder: 45,
    name: "Dr G Veerabhadra Chary",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-46",
    _id: "cm-46",
    displayOrder: 46,
    name: "Dr. M. Rajarao",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-47",
    _id: "cm-47",
    displayOrder: 47,
    name: "Mr. B. Anil Babu",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-48",
    _id: "cm-48",
    displayOrder: 48,
    name: "Mrs. K. Pavani",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-49",
    _id: "cm-49",
    displayOrder: 49,
    name: "Mr. O. Gandhi",
    role: "Technical Program Committee Member",
    designation: "Technical Program Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Technical Program Committee",
    country: "India",
    isActive: true
  },

  // PUBLICITY COMMITTEE (50 - 62)
  {
    id: "cm-50",
    _id: "cm-50",
    displayOrder: 50,
    name: "Mr. P. Vijaya Babu",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-51",
    _id: "cm-51",
    displayOrder: 51,
    name: "Ms. B. Jyothika",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-52",
    _id: "cm-52",
    displayOrder: 52,
    name: "Mr. Syed Nafees Ahamed",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-53",
    _id: "cm-53",
    displayOrder: 53,
    name: "Mrs. D. Tipura",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-54",
    _id: "cm-54",
    displayOrder: 54,
    name: "Ms. K. Raja Rajeswari",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-55",
    _id: "cm-55",
    displayOrder: 55,
    name: "Ms. K. Mercy Bhishayathi",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-56",
    _id: "cm-56",
    displayOrder: 56,
    name: "Mrs. M. Sumalatha",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-57",
    _id: "cm-57",
    displayOrder: 57,
    name: "Mrs. J Davanika",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-58",
    _id: "cm-58",
    displayOrder: 58,
    name: "Mrs. N. Archana",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-59",
    _id: "cm-59",
    displayOrder: 59,
    name: "Ms. K. Vyshnavi",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-60",
    _id: "cm-60",
    displayOrder: 60,
    name: "Mr. Kumar Devapogu",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-61",
    _id: "cm-61",
    displayOrder: 61,
    name: "Mrs. R. Lalitha",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-62",
    _id: "cm-62",
    displayOrder: 62,
    name: "Ms. Y. Sravani",
    role: "Publicity Committee Member",
    designation: "Publicity Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Publicity Committee",
    country: "India",
    isActive: true
  },

  // ORGANIZING COMMITTEE (63 - 82)
  {
    id: "cm-63",
    _id: "cm-63",
    displayOrder: 63,
    name: "Ms. M. Sirisha",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-64",
    _id: "cm-64",
    displayOrder: 64,
    name: "Dr. Shyam Sunder Jannu Soloman",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-65",
    _id: "cm-65",
    displayOrder: 65,
    name: "Mr. B. Krishnakanth",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-66",
    _id: "cm-66",
    displayOrder: 66,
    name: "Mrs. G.Siva Naga Malleswari",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-67",
    _id: "cm-67",
    displayOrder: 67,
    name: "Mrs. K. Jyotsna",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-68",
    _id: "cm-68",
    displayOrder: 68,
    name: "Mr. E. Akhil Babu",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-69",
    _id: "cm-69",
    displayOrder: 69,
    name: "Ms. Sk. Sajida Sultana",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-70",
    _id: "cm-70",
    displayOrder: 70,
    name: "Mrs. V. Sai Spandana",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-71",
    _id: "cm-71",
    displayOrder: 71,
    name: "Mr. D. Balakotaiah",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-72",
    _id: "cm-72",
    displayOrder: 72,
    name: "Mr. P. Venkata Rajulu",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-73",
    _id: "cm-73",
    displayOrder: 73,
    name: "Mr. Sk. Dehtaj",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-74",
    _id: "cm-74",
    displayOrder: 74,
    name: "Ms. Bhavanari Satya Gnyana Sri",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-75",
    _id: "cm-75",
    displayOrder: 75,
    name: "Ms. K. Divya",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-76",
    _id: "cm-76",
    displayOrder: 76,
    name: "Mr. G. Murali",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-77",
    _id: "cm-77",
    displayOrder: 77,
    name: "Mr. K Pavan Kumar",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-78",
    _id: "cm-78",
    displayOrder: 78,
    name: "Mr. M. Anil",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-79",
    _id: "cm-79",
    displayOrder: 79,
    name: "Ms. U. Vara Lakshmi",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-80",
    _id: "cm-80",
    displayOrder: 80,
    name: "Mr. P. Vamsi Krishna",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-81",
    _id: "cm-81",
    displayOrder: 81,
    name: "Ms. P. Deepthi Sowmya",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-82",
    _id: "cm-82",
    displayOrder: 82,
    name: "Ms. K. Anitha",
    role: "Organizing Committee Member",
    designation: "Organizing Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Organizing Committee",
    country: "India",
    isActive: true
  },

  // PROTOCOL AND HOSPITALITY COMMITTEE (83 - 91)
  {
    id: "cm-83",
    _id: "cm-83",
    displayOrder: 83,
    name: "Mrs. Ch. Pushya",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-84",
    _id: "cm-84",
    displayOrder: 84,
    name: "Mr. N. Brahma Naidu",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-85",
    _id: "cm-85",
    displayOrder: 85,
    name: "Mrs. Ch. Swarna Lalitha",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-86",
    _id: "cm-86",
    displayOrder: 86,
    name: "Mrs. K. Sravanthi",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-87",
    _id: "cm-87",
    displayOrder: 87,
    name: "Ms. K. Deepika Sri Sai",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-88",
    _id: "cm-88",
    displayOrder: 88,
    name: "Ms. G. Tejaswi",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-89",
    _id: "cm-89",
    displayOrder: 89,
    name: "Mrs. Sk. Nazeema",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-90",
    _id: "cm-90",
    displayOrder: 90,
    name: "Mrs. G Prasanthi",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  },
  {
    id: "cm-91",
    _id: "cm-91",
    displayOrder: 91,
    name: "Ms. A. Gopya Sri",
    role: "Protocol & Hospitality Committee Member",
    designation: "Protocol & Hospitality Committee Member",
    institution: "VFSTR (Deemed to be University)",
    org: "VFSTR (Deemed to be University)",
    category: "Protocol and Hospitality Committee",
    country: "India",
    isActive: true
  }
];
